apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/shpendnila/nestjs-app
    targetRevision: HEAD
    kustomize:
      images:
      - gcr.io/rubik-web-app-1540579753013/nestjs-app:90f5c805e12701b003301acb3f4899c26eacc1b9
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
