apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: kustomize/overlays/staging
    repoURL: https://github.com/shpendnila/test-app
    targetRevision: HEAD
    kustomize:
      images:
      - gcr.io/rubik-web-app-1540579753013/test-app:0fb279c88a1e0398589baeea01dfa0ecde5f4ba5
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
