apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/shpendnila/test-app
    targetRevision: HEAD
    kustomize:
      images:
      - gcr.io/rubik-web-app-1540579753013/test-app:f2418662eef4677b913f0f8abe0e75266c81faf6
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
