apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgB/qU7SVSGVgHnkhCso9l/6j8CZtphZ46xlAGu5GbTs7aB+KNneHewIBUrY4TqpIHCoh2SNZx8VXYtVWfFH9FSPgs0bJVeq3rTo+tGJriCbVL8LD9gXh25TqPFSdX16IQFp+sQdBQlDMWMx9gGXwqx19vhPdQ8vstlXExFumOtTxIxHmgmQ8lOdkG9NcJiDnHXaPQ08ORttNRegemGiMBaCaI+GCaAHOU8i8SXAtCwNAz912yJTLrj8ve8gQesbsxybIotsrJNNgm4AuPkf6hezB7RFqcNIB4G52wfvbYOp/jz/lUCeJ8Nr+eKydCgjqpqW5SHeOEL7SEsD/lQxPAig6bR9jBdbuPIN4xC8e73LRYFUxF5pVtV4HAoqut6Pc2wtZDfGqijxTQFl35nN6/Lt6ovvIM5GubF7MpDGMQvul5JLHd1VojhudJQdBFKJzp4Ob0lstNNUbhtbbtWAJIm2MiUR3A2R+3QkZijyMesQOtaW53XFYdHUK1FrFpqmd+VpU2hgId/hpdhUMl03Q1NqfV1lk4cd9rChofrU1hAVdVhIkDVAzR6JvKAJ/VsgU5bngn5R7qMtKLRj2lL6WUqUif2Y0S2PV03f4PCZvuNuIGEJzAqT5NBgaLzrGUb6xCeQ/M8OuTTMSKPWYe86yFdmIy5NHtskbzbW3bJ9FM38mMoAZ2tAegf+e+PdtBkPIUfFir32/E/hVZn0LSLo6/D0bBxqicpSYkiC4gteE5NaCfYkTq8dFUPHsQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

